name: Test
on: push
jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: add ssh key
  #       uses: shimataro/ssh-key-action@v2
  #       with:
  #         key: ${{ secrets.DEPLOY_KEY }}
  #         known_hosts: 'known_host'
      
      # - name: Adding Known Hosts
      #   run: ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      # - name: Deploy compose
      #   run: ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "sudo docker login sudo docker-compose pull && sudo docker-compose up -d"

  deploy:
    runs-on: self-hosted
    # needs: test
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          path: $GITHUB_WORKSPACE/test
      - name: login to docker registry
        uses: docker/login-action@v1.13.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}