name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: add ssh key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          known_hosts: 'known_host'
      
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts